Update ktext.md
dortania/OpenCore-Install-Guide pull request #164
Opened 2020-09-27 21:07 UTC by 1Revenger1

2020-09-27 21:56 UTC, dhinakg requested changes

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
> +* [Rehabman's VoodooPS2](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller)
```suggestion
* [RehabMan's VoodooPS2](https://github.com/RehabMan/OS-X-Voodoo-PS2-Controller)
```

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
> +  * For older systems with PS2 keyboards, Mice and Trackpads
```suggestion
  * For older systems with PS2 keyboards, mice, and trackpads
```

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
>    * For systems with PS2 Keyboards, Mice and Trackpads
```suggestion
  * For systems with PS2 keyboards, mice, and trackpads
```

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
>    * Requires OS X 10.11 or newer for MT2 functions
```suggestion
  * Requires OS X 10.11 or newer for MT2 (Magic Trackpad 2) functions
```

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
> +  * For if you need to use VoodooPS2 for 10.6-10.11, or otherwise don't want to use VoodooInput for MT2 functions
```suggestion
  * Use if you need 10.6-10.11 support, or otherwise don't want to use VoodooInput for MT2 functions
```

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
> +  * For systems with Synaptic SMBus-based devices, mainly for trackpads and trackpoints.
```suggestion
  * For systems with Synaptics' SMBus-based devices, mainly for trackpads and trackpoints.
```

2020-09-27 21:56 UTC, dhinakg commented on ktext.md
> +  * For systems with ELANs SMBus-based devices, mainly for trackpads and trackpoints.
```suggestion
  * For systems with ELAN's SMBus-based devices, mainly for trackpads and trackpoints.
```

2020-09-29 02:53 UTC, dhinakg approved these changes
trash

2020-09-29 03:02 UTC, 1Revenger1 commented
oh....
darn

2020-10-02 15:42 UTC, merged