Change "Format to FAT32" to "Format to HFS+"
dortania/OpenCore-Install-Guide pull request #330
Opened 2022-01-20 22:11 UTC by XgamesMFZB

I was NOT able to install legacy OS X (Mountain Lion) with online/recovery-only installer on a FAT32 USB stick.  On 2 separate attempts, I only had success with an HFS+ formatted drive.  Formatting the drive as FAT32 will cause "Install OS X Mountain Lion" to do not appears in the OpenCore picker even with HideAuxiliary set to False.  As soon as I formatted as HFS+ and repeated the steps, the installer was accessible and installed with no issues.

If FAT32 is indeed incorrect, this should be corrected.  Thanks.

2022-01-23 06:00 UTC, alyxferrari commented
The part of the guide you edited is talking about making the drive with OpenCore and the BaseSystem image on it. I'm assuming when you did it, the drive with the BaseSystem image didn't have OpenCore as well because otherwise, the BIOS would not have been able to boot it.

This seems like a good change (as long as you mention that it's **specifically** for Mountain Lion), it's just in the wrong place.

2022-01-23 15:39 UTC, XgamesMFZB commented
Thank you for following to my first contribution.

Not sure I understand fully, I actually formatted the USB as GPT in HFS+ format as per screenshot, and then I followed the guide and added the EFI folder including OpenCore to the EFI partition (Which Disk Utility immediately formated as FAT32, as it should).  I suppose this is what you mean, because EFI is always FAT32 and bootable regardless - The difference is that as complete FAT32, Install Mountain Lion would never show up in the picker.  I imagine this is the same process for Lion/Mountain Lion/Mavericks, which no longer offer offline installers on the guide and must be installed online-only.

I'm confused because the "Offline Installer" also format as HFS+ ( https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#downloading-macos-legacy-os ) - as I understand, OpenCore would load the HfsPlus.efi / HfsPlusLegacy.efi driver, which would allow the HFS+ installer partition to be listed and bootable, however FAT32 would obviously never work.

But I'm pretty convinced you know this already for sure, I'm only confused because this seems correct to me?  If I'm wrong (or in the wrong place as I could be, as a first-time user), please let me know.

Thank you

2022-01-23 22:35 UTC, alyxferrari commented
Yeah, so you added OpenCore to the ESP (which as you said is FAT32) and then put macOS on a separate HFS+ partition.

The change you made looks like it's instructing people to put both OpenCore and a macOS image on the same HFS+ partition, meaning OpenCore would not be bootable because the UEFI firmware in PCs can't read HFS+.

2022-01-23 22:39 UTC, alyxferrari commented
Also, for what it's worth, I am very active on the AMD OS X Discord server and have never seen this issue with booting newer versions of macOS, people always put the BaseSystem.dmg and chunklist on the same FAT32 partition as OpenCore with no issues. The purpose of the HfsPlus UEFI driver, in this case, would be reading the DMG itself, because the contents of the DMG are formatted as HFS+ despite being placed in a FAT32 partition.

2022-01-23 22:55 UTC, 1Revenger1 requested changes
If booting older macOS versions (believe 10.7-10.9?) you need OpenPartitionDxe.efi.
The guide assumes that you are putting recovery and OpenCore on the same partition. Partitioning it as HFS+ would make it impossible for any computer that's not a Mac to boot it. This would work I believe if you had a separate HFS+ volume which you put the recovery image on, since OpenCore will scan it after loading HFSPlus.efi.

2022-01-23 23:02 UTC, XgamesMFZB commented
Thank you for following-up.  I did not knew about booting from the DMG, as it was the first time I did an online install.
Some people had trouble like that on Reddit as well: https://www.reddit.com/r/hackintosh/comments/ke53pf/opencore_does_not_show_boot_option/

I will redo the Mountain Lion online-installer and on full FAT32 this time, JUST in case I forgot ScanPolicy 0 or something.  I'll report back ASAP.

2022-01-23 23:27 UTC, XgamesMFZB commented
Update:
That's right actually, my apologies - ScanPolicy was set to 33518339 omg (I reused the EFI so many times for that machine, for different macOS versions with only small changes...).  Set it up to 0 and then the FAT32 installer showed up and loaded.  With the installer set up as 33518339, it only showed up partitioned as HFS+.

I am not sure why the offline installer ( https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-the-installer ) instructs to format as HFS+ while online FAT32 - I learned the offline method first, so that was new to me.  If that makes sense, I also have a macOS partition installed on the HDD already, if you count that as a separate volume?

Anyway it works now, we can close haha, I apologize and thank you for confirming :)

2022-01-24 02:00 UTC, 1Revenger1 commented
> Update: That's right actually, my apologies - ScanPolicy was set to 33518339 omg (I reused the EFI so many times for that machine, for different macOS versions with only small changes...). Set it up to 0 and then the FAT32 installer showed up and loaded. With the installer set up as 33518339, it only showed up partitioned as HFS+.
> 
> I am not sure why the offline installer ( https://dortania.github.io/OpenCore-Install-Guide/installer-guide/mac-install.html#setting-up-the-installer ) instructs to format as HFS+ while online FAT32 - I learned the offline method first, so that was new to me. If that makes sense, I also have a macOS partition installed on the HDD already, if you count that as a separate volume?
> 
> Anyway it works now, we can close haha, I apologize and thank you for confirming :)

Yep, scanpolicy would do it, lol.
And the macOS installer is HFS, except it's extracted to that partition rather than just a DMG that's loaded into memory. When the USB is partitioned as well, it creates a FAT32 EFI partition in addition to the HFS+ partition you create.

2022-01-24 02:00 UTC, closed without merging